// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAf2xRYehCWvhbBOr2u2F0gdsckJPAdDvA',
    appId: '1:717899257312:web:0b745699382b181bac8785',
    messagingSenderId: '717899257312',
    projectId: 'myportfolio-be979',
    authDomain: 'myportfolio-be979.firebaseapp.com',
    storageBucket: 'myportfolio-be979.appspot.com',
    measurementId: 'G-PG9WFCQE83',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAoDlsRg6b-fhAMH0bFvOD99AeMJaccwoM',
    appId: '1:717899257312:android:acfb55ad580044dcac8785',
    messagingSenderId: '717899257312',
    projectId: 'myportfolio-be979',
    storageBucket: 'myportfolio-be979.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyByQTvcy8iT-4Ruj8-IO1spX7C3ZV70a9I',
    appId: '1:717899257312:ios:7e36153009aada47ac8785',
    messagingSenderId: '717899257312',
    projectId: 'myportfolio-be979',
    storageBucket: 'myportfolio-be979.appspot.com',
    iosBundleId: 'com.example.maxwellNdungu',
  );

}